# Generated by Django 3.2.3 on 2021-08-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_root', to='fledit.tripmodel', verbose_name='旅程番号'),
        ),
        migrations.AlterField(
            model_name='tripmodel',
            name='images',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='', verbose_name='写真(1枚のみ)'),
        ),
    ]
