# Generated by Django 3.2.3 on 2021-09-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0002_auto_20210828_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='rootcategory',
            field=models.CharField(max_length=100, verbose_name='旅程カテゴリ'),
        ),
    ]
