# Generated by Django 3.2.3 on 2021-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0003_alter_rootmodel_rootcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootmodel',
            name='arrdate',
        ),
        migrations.RemoveField(
            model_name='rootmodel',
            name='depdate',
        ),
        migrations.AddField(
            model_name='rootmodel',
            name='earlydep',
            field=models.BooleanField(default=0, verbose_name='前日発'),
        ),
        migrations.AddField(
            model_name='rootmodel',
            name='latearr',
            field=models.BooleanField(default=0, verbose_name='翌日着'),
        ),
    ]
