# Generated by Django 3.2.3 on 2021-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0004_auto_20210909_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='earlydep',
            field=models.BooleanField(blank=True, verbose_name='前日発'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='latearr',
            field=models.BooleanField(blank=True, verbose_name='翌日着'),
        ),
    ]
