# Generated by Django 3.2.3 on 2021-09-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0005_auto_20210926_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootmodel',
            old_name='rootid',
            new_name='tripid',
        ),
    ]
