# Generated by Django 3.2.3 on 2021-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0006_rename_rootid_rootmodel_tripid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='rootmemo',
            field=models.TextField(blank=True, max_length=1000, verbose_name='詳細メモ'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='roottitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='行路の概要'),
        ),
    ]
