# Generated by Django 3.2.3 on 2021-11-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0007_auto_20211123_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='rootcategory',
            field=models.CharField(max_length=100, verbose_name='行程カテゴリ'),
        ),
    ]
