# Generated by Django 3.2.3 on 2021-11-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0008_alter_rootmodel_rootcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdtitle', models.CharField(max_length=50, verbose_name='ToDoタイトル')),
                ('tdcontext', models.TextField(blank=True, max_length=1000, verbose_name='ToDo概要')),
                ('tddid', models.BooleanField(blank=True, verbose_name='完了済みか')),
                ('tripid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tdlist', to='fledit.tripmodel', verbose_name='旅程番号')),
            ],
        ),
    ]
