# Generated by Django 3.2.3 on 2021-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0009_todomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='tdpriority',
            field=models.CharField(default=1, max_length=50, verbose_name='優先度'),
            preserve_default=False,
        ),
    ]
