# Generated by Django 3.2.3 on 2022-01-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0010_todomodel_tdpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='rootid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_root', to='fledit.rootmodel', verbose_name='行程データ'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='arrtime',
            field=models.TimeField(verbose_name='到着時刻'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='deptime',
            field=models.TimeField(verbose_name='出発時刻'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='tripid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_root', to='fledit.tripmodel', verbose_name='旅行データ'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='tripid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tdlist', to='fledit.tripmodel', verbose_name='旅行データ'),
        ),
    ]
