# Generated by Django 3.2.3 on 2022-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0011_auto_20220111_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='arrtime',
            field=models.TimeField(verbose_name='到着時刻/終了時刻'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='depspot',
            field=models.CharField(max_length=50, verbose_name='出発地点/場所'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='deptime',
            field=models.TimeField(verbose_name='出発時刻/開始時刻'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='earlydep',
            field=models.BooleanField(blank=True, verbose_name='前日発/前日'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='latearr',
            field=models.BooleanField(blank=True, verbose_name='翌日着/翌日'),
        ),
        migrations.AlterField(
            model_name='rootmodel',
            name='roottitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='行路/イベントのタイトル'),
        ),
    ]
