# Generated by Django 3.2.3 on 2022-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0012_auto_20220112_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmodel',
            name='arrspot',
            field=models.CharField(blank=True, max_length=50, verbose_name='到着地点'),
        ),
    ]
